// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsw30QiO3poVtr5eglLeph27xIQZmfXn8',
    appId: '1:91219740751:web:05112a9106b6aa0ef2023a',
    messagingSenderId: '91219740751',
    projectId: 'tcc-meu-foco-total',
    authDomain: 'tcc-meu-foco-total.firebaseapp.com',
    storageBucket: 'tcc-meu-foco-total.appspot.com',
    measurementId: 'G-GDSMWZ30WL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnQSwWUoMG_UCuY898CLEhutILNVv2YKU',
    appId: '1:91219740751:android:70ce3cfafa387ea5f2023a',
    messagingSenderId: '91219740751',
    projectId: 'tcc-meu-foco-total',
    storageBucket: 'tcc-meu-foco-total.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUacQFhMSELzN8J5d_OtHUx8Ep745fl64',
    appId: '1:91219740751:ios:e1956a1e802d20eef2023a',
    messagingSenderId: '91219740751',
    projectId: 'tcc-meu-foco-total',
    storageBucket: 'tcc-meu-foco-total.appspot.com',
    iosBundleId: 'com.example.focoAlternativo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUacQFhMSELzN8J5d_OtHUx8Ep745fl64',
    appId: '1:91219740751:ios:6d504446e06d0b75f2023a',
    messagingSenderId: '91219740751',
    projectId: 'tcc-meu-foco-total',
    storageBucket: 'tcc-meu-foco-total.appspot.com',
    iosBundleId: 'com.example.focoAlternativo.RunnerTests',
  );
}
